### ISSUE TITLE
Long loading times

### ISSUE THREAD

**Issue by Electricz1337** [RotherOSS/otobo-docker#126]
We just set up otobo using docker in our environment.

When accessing via Browser we face long loading times of the index file:

![image](https://github.com/RotherOSS/otobo-docker/assets/30772723/1fd0b36e-0548-4816-b89e-d6f3ab9d8a5d)

Sometimes it also throws this message:

![image](https://github.com/RotherOSS/otobo-docker/assets/30772723/4ca5e099-4a01-4504-925c-59b94bdc11f8)

It appears on different Browsers:

Google Chrome Version 119.0.6045.160
Microsoft Edge Version 119.0.2151.58
Thorium Version 117.0.5938.157
Firefox Version 119.0.1

I also tested each Browser also in Inkognito Mode 

We also tried with and without the nginx reverse proxy

**Comment by hamzahjamad** [comment]
I have the same problem, enabling cache doesn't speed up the performance. Any ideas on what to do next?

**Comment by StefanRother-OTOBO** [comment]
Hi,

Unfortunately, we cannot understand this issue. We install OTOBO almost exclusively with docker and docker-compose and the performance is better than with the native installation.

The following comes to mind, maybe it helps:

- Was the installation performed as specified in the documentation https://doc.otobo.org/manual/installation/10.1/en/content/installation-docker.html? 

If so, OTOBO should be available with good performance. 

Other ideas:

- The first call of index.pl always takes a little longer, as all indices have to be set up first.

- Sometimes it helps to deactivate RedisCache in the Kernel/Config.pm file and switch to FS. On some systems, our redis configuration is slower than the native cache on the file system.

- Otherwise observe the resource utilisation.

However, since we do not receive any other feedback like this from our customers and have no starting point, I will close the issue.

You are welcome to reopen it when further information is available. Otherwise, you are welcome to contact sales@otobo.de (paid support contract required) so that we can analyse and resolve the problem with your instance.

I hope I was able to help,

Stefan
Team OTOBO

**Comment by tr-electronic-edv** [comment]
Hallo Stefan,

First of all thank you for the great product. I'm setting it up for several days and still have many items in admin menu that I didn't learn how to use yet :smile:

Though I have same perfomance problem - a fresh otobo-docker installation runs quite slow.

I set up Otobo groups with LDAP sync, so the long first login into the Agent zone (~15 sec) is probably normal.

## Problem 
The response time of the web-interface (tickets page, admin menu) is slow. 
Comparing with a test Otobo instance in internet, the docker-otobo has x3-x4 longer reaction time - uncomfortable.

Here I login as a client user:
<img width="1378" height="124" alt="Image" src="https://github.com/user-attachments/assets/a4635d95-2a7b-4fbb-8f06-4ea363d2ac4d" />

Here I've added a new Queue as an Admin:
<img width="1146" height="153" alt="Image" src="https://github.com/user-attachments/assets/5cd60341-600a-42b4-be2e-4d10b0d1756b" />

Here I've added a ticket:
<img width="1131" height="109" alt="Image" src="https://github.com/user-attachments/assets/f9f2b5eb-ecae-4b06-b869-f9ddb3511de7" />

I wouldn't say it's impossible to work, but the interface feels slow.

> However, since we do not receive any other feedback like this from our customers and have no starting point, I will close the issue

Other users experience similar problem: https://otobo.io/forums/topic/leistungs-probleme-nach-installation/ and didn't found (or didn't posted) a solution.

## Environment
Ubuntu 24.04 VM, 32 RAM, 4 cpu cores, SSD
```
sudo hdparm -Tt /dev/sda

/dev/sda:
 Timing cached reads:   22664 MB in  2.00 seconds = 11349.49 MB/sec
 Timing buffered disk reads: 3146 MB in  3.00 seconds = 1048.08 MB/sec
```

I use a local Mariadb with 12 Gb InnoDB cache, so even the slow disk IO should not affect Otobo.

## Possible reasons
- I use SimpleHttpAuth and Kerbeos. May each http request to Otobo be authorized against AD in background? This could explain the high response time.
- incorrect Nginx or Redis cache settings in the default Docker images?

> Sometimes it helps to deactivate RedisCache in the Kernel/Config.pm file and switch to FS. On some systems, our redis configuration is slower than the native cache on the file system.

I've deactivated Redis
<img width="658" height="203" alt="Image" src="https://github.com/user-attachments/assets/405df751-a53b-4e21-a086-ecf185e8b5ec" />

Still the Customer user page first load time is about 6 sec
<img width="783" height="207" alt="Image" src="https://github.com/user-attachments/assets/caaa7592-5125-4fc3-b557-74e19890a62c" />
