### ISSUE TITLE
Problems with database on upgrade from 10.1 to 11.4

### ISSUE THREAD

**Issue by wornet-aer** [RotherOSS/otobo-docker#139]
I've just tried running an upgrade using `otobo-docker` using the `scripts/update.sh` from version 10.1 to 11.0.4 Unfortunately it seems to have broken the OTOBO database.

```
Prüfung Tabellenexistenz (article_version, article_flag_version, article_data_mime_version, article_data_mime_att_version, article_version_history, time_accounting_version, form_cache, dynamic_field_script_event, frontend_mask_definition, imexport_template, imexport_object, imexport_format, imexport_mapping, imexport_mapping_object, imexport_mapping_format, imexport_search, translation_item)

In der Datenbank fehlen Tabellen.
```

In the system log the following errors occur:
`Unknown column 'index_value' in 'field list', SQL: 'SELECT id, value_text, value_date, value_int, field_id, index_value, index_set`
`Table 'otobo.article_version' doesn't exist, SQL: 'SELECT * FROM (`
`Need TicketID!`
`Need ArticleID!`

Maybe somehow the database was not correctly migrated to the new version?
I'll rollback to my last snapshot now, but any tips/hints on how to get this sorted out would be appreciated! :-)

**Comment by svenoe** [comment]
Hi Andreas,

for version upgrades you cannot use the script anymore, because there is some database specific stuff which has to be done during the upgrade, too. Please stick to the manual flow: https://doc.otobo.org/manual/installation/11.0/en/content/updating-docker.html#update-otobo

(Importantly `docker-compose exec web perl scripts/DBUpdate-to-11.0.pl` has to be executed before `do_update_tasks`.)

Best regards, Sven

**Comment by wornet-aer** [comment]
I had tried to find this information somewhere in the GitHub repos, but obviously I've missed the official docs then. 
Thanks for your help!

**Comment by svenoe** [comment]
Hi Andreas, just to save you some time - please wait with your update for one day, we had an oversight with an CK5-change we made, and will release 11.0.5 today or tomorrow, to fix this.
