### ISSUE TITLE
Make the database server configurable not only password

### ISSUE THREAD

**Issue by possebon** [RotherOSS/otobo-docker#74]
Although it's possible to run the database as a container, it's known that databases growths fast and usually can have performance issues due it's running inside containers.

It would be important to have a way to configure on .env file the **host**, **database name**, **user** and **password**.

This allows for more flexible setups.

**Comment by bschmalhofer** [comment]
Hello Jose,

yes this is a good idea. In this scenario this would encompass splitting _docker-compos/otobo-base.yml_ into otobo-base.yml and otobo-db.yml, so that users can choose to not even start the database. I'll try to make that happen in OTOBO 10.1.x. Of course the same can be said for the other services, but a line has to be drawn somewhere.

Did you already try to run the database outside of docker? This should be easily possible by  specifying the appropriate settings when running _installer.pl_ in the WebGUI. 

For avoiding the then useless MariaDB in Docker you can:

-  docker-compose down
- copy _docker-compose/otobo-base.yml_ to  _docker-compose/otobo-base-without-db.yml_
- remove the db service in the copied .yml file
- adapt COMPOSE_FILE in _.env_
- docker-compose up -d

Best regards,
   Bernhard

**Comment by bschmalhofer** [comment]
When this is implemented than the service _db_ should be moved out of _docker-compose/otobo-base,yml_ into _docker-compose/otobo-db.yml_ . This allows the setup in _.env_ to avoid running an unused service.

**Comment by bschmalhofer** [comment]
First there is not an use case for adding host, database name, user and user password to the _.env_ file. Specifiying a non-Docker database can already be done when running installer.pl when installing the system.

So the only remaining feature is to prohibit the service _web_ from starting up. Of course this is not strictly necessary, but an idling service is not really elegant. There has been a long discussion about a blacklist flag in the Docker compose community:  
https://github.com/docker/compose/issues/1896 . However the suggested feature was not implemented. In that issues, or in related issues, three workarounds were proposed:

1. split the service web into a separate config file and don't include that file in _.env_
2. specifiy the list of needed services, that is all services excluding db, when starting up
3. Use the option `--scale db=0` when starting up

re 1.: This is the same solution as proposed above. The downside is that existing _.env_ files would have to be updated. This should be avoided
re 2.: Currrenty when running  `docker-compose up -d elastic redis web daemon nginx` then db is started anyways. That is because db has been declared to be a dependency of web.
re 3.: This looks like a sensible compromise. The only downside is that the MariaDB is fetched anyways, but that is IMHO acceptable.

TODO: document the possible option 3 in the installation manual

**Comment by bschmalhofer** [comment]
Closing this issue as I have no better idea than the  `--scale db=0` trick.
